### ISSUE TITLE
No call to get_session before chained query and `template_id` ref

### ISSUE THREAD

**Issue by pmslavin** [hydraplatform/hydra-base#128]
In `get_templatetype()` line 1098 doesn't call the `get_session` function before using the chained `query()`...

https://github.com/hydraplatform/hydra-base/blob/7d46b6ea307a571cd858d3e03ef51094eb27dd58/hydra_base/db/model.py#L1096-L1102

...and the subsequent line 1099 has `self.template_id` instead of `self.child_template_id`(?).

**Comment by knoxsp** [comment]
Which branch is this on?

**Comment by pmslavin** [comment]
It's on `master`.

**Comment by knoxsp** [comment]
Check out the template inheritance branch. A lot of work has been done on that, owing to issues highlighted by HWI

**Comment by pmslavin** [comment]
OK - I see it is now fixed on `template_inheritance` - still present on `125-fix-child-template-deletion`.

I'll close this as will be fixed by merge of `template_inheritance`.
