### ISSUE TITLE
Dataset name truncated to different lengths

### ISSUE THREAD

**Issue by pmslavin** [hydraplatform/hydra-base#141]
The dataset name is still truncated to 60 chars here...

https://github.com/hydraplatform/hydra-base/blob/b7dd7fa4e4b2abc8625f15bb94110fc97e997e4e/hydra_base/lib/data.py#L582
...but has been expanded to 200 chars above...
https://github.com/hydraplatform/hydra-base/blob/b7dd7fa4e4b2abc8625f15bb94110fc97e997e4e/hydra_base/lib/data.py#L544

Could define a local `DATASET_NAME_MAX_LENGTH` but there are enough cases like this around that a `hydra.constants` module to collect all such definitions into a single place might be useful.

**Comment by knoxsp** [comment]
I must have forgotten to push that change, as it's certainly fixed
somewhere! I'll check and update ASAP, or feel free to make a PR
