### ISSUE TITLE
Reassign scoped attributes within projects

### ISSUE THREAD

**Issue by pmslavin** [hydraplatform/hydra-base#176]
This issue is to:
* Identify issues with reassigning scoped attributes not respecting the bounds of projects: add a test which isolates this.
* Ensure that promotion of attrs from (i) network => project scope and also from (ii) child_project => parent_project scope are both performed correctly.
* Ensure any attr lookup routines are aware of the relevant scopes and that the network => project => parent_project => global hierarchy is always respected in lookups from narrower to broader scopes.

**Comment by knoxsp** [comment]
The specific issue which prompted this is a situation where:

1. A scoped attribute `attra` was added to a project, and associated resource attributes were created
2. A new project was created, and a scoped attribute `attrb` with the same name & dimension as `attra` was added to this project.
3. The reassigning code attempted to delete `attra`, even though it's in an unrelated project.
