### ISSUE TITLE
Add management of input files

### ISSUE THREAD

**Issue by knoxsp** [hydraplatform/hydra-base#196]
A common use-case is for input data to be located in separate input files such as XLS or CSV.
This is to request the abiltiy to upload files to a project, or to store them in a location which enables predictable programmatic access, and for those files to be retrieved when necessary.

**Comment by pmslavin** [comment]
There are some similarities between this and the [hydra-pywr filecache](https://github.com/pywr/hydra-pywr/blob/22-unify-functionality/hydra_pywr/filecache.py) in terms of looking up data files from a central index that is abstracted from filesystem paths.
