### ISSUE TITLE
Unable to set the parent_id of a project to None

### ISSUE THREAD

**Issue by knoxsp** [hydraplatform/hydra-base#232]
In the update_project function, and in the move_project funciton it is not possible to move a project to the top level, by setting its parent_id to None. In both cases, it returns an error that `Project ID None does not exist`, because there is no check for this in the code.

We need to add support for this in both the update_project and move_project functions, and then update the tests appropriately

**Comment by pmslavin** [comment]
So what we want is for this hypothetical test to pass...

```python
    def test_remove_project_parent(self, client, projectmaker, networkmaker):
        orig_parent_proj = projectmaker.create()
        child_proj = projectmaker.create(parent_id=orig_parent_proj.id)

        proj_i = client.get_project(child_proj.id)
        assert proj_i.parent_id == orig_parent_proj.id

        # Remove parent of child_proj
        proj_i.parent_id = None
        client.update_project(proj_i)

        # Verify retrieved project now has no parent
        proj_i = client.get_project(child_proj.id)
        assert proj_i.parent_id is None
```

...whereas it fails currently.

So can we just add a separate `remove_project_parent` func which just sets the parent_id to `None`?  This can then be delegated to in `update_project` and `move_project` when it is identified that a project's `parent_id` is being set to `None`.

**Comment by knoxsp** [comment]
Yep exactly
