### ISSUE TITLE
Zope.sqlalchemy version 1.2 renames ZopeTransactionExtension class

### ISSUE THREAD

**Issue by pmslavin** [hydraplatform/hydra-base#91]
Version 1.2 of [Zope Sqlalchemy](https://pypi.org/project/zope.sqlalchemy/#id1) has renamed the `ZopeTransactionExtension` class to `ZopeTransactionEvents`.

This is in use at two locations in `hydra_base/db/__init__.py`:

https://github.com/hydraplatform/hydra-base/blob/36c01a7b130ae931d858c03d0dafacb9f7ce67cc/hydra_base/db/__init__.py#L23

...and...

https://github.com/hydraplatform/hydra-base/blob/36c01a7b130ae931d858c03d0dafacb9f7ce67cc/hydra_base/db/__init__.py#L103

The former name has been retired so `L23` results in an `ImportError`.

**Comment by knoxsp** [comment]
Giovanni solved this by using the 'register' function in #93
